language: php

php:
    - 7.2
    - 7.3
    - 7.4
    
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - sudo apt-get update
    - sudo apt-get -y install inotify-tools fswatch
    - composer install

script:
    - composer integrate
