dist: bionic
language: php

php:
    - 7.2
    - 7.3
    - 7.4
    
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - wget https://github.com/facebook/watchman/releases/download/v2020.09.14.00/watchman-v2020.09.14.00-linux.zip
    - unzip watchman-v2020.09.14.00-linux.zip
    - sudo mv watchman-v2020.09.14.00-linux/bin/watchman /usr/bin/watchman
    - sudo apt-get -y install inotify-tools fswatch
    - composer install

script:
    - composer integrate
